ARG KEYCLOAK_BASE=quay.io/keycloak/keycloak@sha256:0f198be292568439d700cdbfb893e69a6009bb43a94a06a945b1d3d506c76b13

FROM ${KEYCLOAK_BASE} AS builder

ENV KC_DB=postgres \
    KC_HEALTH_ENABLED=true \
    KC_METRICS_ENABLED=true

WORKDIR /opt/keycloak
RUN /opt/keycloak/bin/kc.sh build \
    --db=postgres \
    --health-enabled=true \
    --metrics-enabled=true

FROM ${KEYCLOAK_BASE}

ARG SCIFORGE_BASE_DIGEST
ARG SCIFORGE_BUILD_TIMESTAMP
ARG SCIFORGE_CONTAINERFILE_SHA256
ARG SCIFORGE_RELEASE_ID

LABEL org.opencontainers.image.title="SciForge Keycloak optimized" \
      org.opencontainers.image.version="26.7.0" \
      org.opencontainers.image.created="${SCIFORGE_BUILD_TIMESTAMP}" \
      org.opencontainers.image.revision="${SCIFORGE_RELEASE_ID}" \
      cn.sciforge.keycloak.base-digest="${SCIFORGE_BASE_DIGEST}" \
      cn.sciforge.keycloak.containerfile-sha256="${SCIFORGE_CONTAINERFILE_SHA256}"

COPY --from=builder --chown=1000:0 /opt/keycloak/ /opt/keycloak/

ENV KC_DB=postgres \
    KC_HEALTH_ENABLED=true \
    KC_METRICS_ENABLED=true

USER 1000
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
